name: movie_recommender
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - cudatoolkit=11.6
  - numpy=1.23.5
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - networkx=3.1
  - gudhi=3.7.0
  - pot=0.9.0
  - pip:
    - torch-geometric==2.3.1
    - qiskit==1.0.2
    - qiskit-machine-learning==0.5.0
    - qiskit-aer==0.12.0
    - pennylane==0.30.0
    - tqdm==4.65.0
    - fastdtw==0.3.4 