name: movie_recommender
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - pytorch-cpu>=1.10.0
  - torchvision-cpu>=0.11.0
  - tqdm>=4.62.0
  - jupyter>=1.0.0
  - mkl>=2021.0
  - openmp>=11.0
  - pip:
    - tensorboard>=2.7.0
    - optuna>=2.10.0
    - lightfm>=1.16
    - implicit>=0.4.4
    - scipy>=1.7.0
    - networkx>=2.6.0
    - pymoo>=0.5.0
    - mlflow>=1.20.0
    - numba>=0.55.0
    - joblib>=1.1.0 